apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloakash-deployment
  labels:
    app: helloakash-deployment
spec:
  selector:
    matchLabels:
      app: helloakash-deployment
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: helloakash-deployment
    spec:
      containers:
        - name: helloakash-deployment
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: 80