
apiVersion: v1
kind: Service
metadata:
  name:helloakash-deployment
  labels:
    app: helloakash-deployment
spec:
  ports:
    - port: 80
      protocol: TCP
      name: nginx
  selector:
    app: helloakash-deployment
  type: LoadBalancer
