
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  ports:
    - port: 80
      protocol: TCP
      name: nginx
  selector:
    app: nginx-deployment
  type: LoadBalancer
